recipe: default.v1


language: en


pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  min_ngram: 1
  max_ngram: 2
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 3
  max_ngram: 5
- name: DIETClassifier
  epochs: 60
  constrain_similarities: true
  entity_recognition: true
- name: EntitySynonymMapper
- name: FallbackClassifier
  threshold: 0.35
  ambiguity_threshold: 0.1


policies:
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "utter_fallback"
  enable_fallback_prediction: true
- name: MemoizationPolicy
  max_history: 5
- name: TEDPolicy
  max_history: 5
  epochs: 40
assistant_id: 20250828-222348-pizzicato-molding
